image: alpine:latest

stages:
  - deploy

pages:
  image: cm0x4d/jsdoc
  stage: deploy
  script:
  - mkdir jsdocs
#  - jsdoc docs/js/*.js -d jsdocs
  - mkdir public
  - mv jsdocs docs/
  - cp -R docs/* public/
  artifacts:
    paths:
    - public
  only:
  - master
